language: go
go:
  - 1.9.2
env:
  global:
    - SSH_KEY="travis"
    - GIT_NAME="Bernardo Meurer"
    - GIT_EMAIL="meurerbernardo@gmail.com"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="master"
    - TEMP_DIR=$(sudo mktemp -d /tmp/$REPO_NAME.XXXX)
before_install:
  - openssl aes-256-cbc -K $encrypted_61d8d5d18380_key -iv $encrypted_61d8d5d18380_iv -in travis.enc -out travis -d
before_script:
  - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
  - go get -u -v github.com/spf13/hugo
script:
  - git submodule init
  - hugo
after_success:
  - chmod a+x ./scripts/deploy.sh
  - ./scripts/deploy.sh
