baseURL = "https://lovesegfault.com/"
languageCode = "en-us"
title = "null pointer test"
theme = "kiera"
copyright = "Copyright &copy; 2019 - Bernardo Meurer"
enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true
canonifyurls = true

googleAnalytics = "UA-75408326-1"
summaryLength = 30

pygmentsStyle = "dracula"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsOptions = "linenos=1"


[author]
    name = "Bernardo Meurer"
    github = "lovesegfault"
    linkedin = "meurerbernardo"
    twitter = "lovesegfault"
    email = "meurerbernardo@gmail.com"

[params]
	tagline = "Ideas expressed here are nobody's."
    description = "Bernardo's ramblings and non sequuntur"
    googleAnalytics = "UA-75408326-1"
    smartToc = true
    paginate = 10
