baseURL = "https://lovesegfault.com/"
languageCode = "en-us"
title = "null pointer"
theme = "kiera"
copyright = "Copyright &copy; 2019 - Bernardo Meurer"
enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true
canonifyurls = true

googleAnalytics = "UA-75408326-1"
summaryLength = 30

[author]
    email = "bernardo@meurer.org"
    github = "lovesegfault"
    linkedin = "meurerbernardo"
    name = "Bernardo Meurer"
    twitter = "lovesegfault"

[params]
    description = "Bernardo's ramblings and non sequuntur"
    googleAnalytics = "UA-75408326-1"
    paginate = 10
    smartToc = true
    tagline = "Ideas expressed here are nobody's."
    utterancesIssueTerm = "title"
    utterancesRepo = "lovesegfault/lovesegfault.github.io"

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
[markup.goldmark.parser]
    attribute = true
    autoHeadingID = true
[markup.goldmark.renderer]
    hardWraps = false
    unsafe = false
    xHTML = false
[markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    style = "dracula"
